// M2.5.2 -- OAEP x real Chromium (Playwright), encrypt and decrypt.
// Reuses M1's real validateOaepEncryptRequest/validateOaepDecryptRequest
// (pure JS contract logic). Only the actual crypto.subtle call executes
// inside the real browser, importing the externally-supplied RSA-3072 key
// as JWK (WebCrypto's own RSA key import format) -- oaepWebCrypto*
// (src/adapters/webcrypto/oaep.ts) is Node-bound and cannot run in a
// page.evaluate() context, same reasoning as HKDF/GCM.

import { validateOaepEncryptRequest, validateOaepDecryptRequest, type OaepEncryptRequest, type OaepDecryptRequest } from '../../src/contract/oaep.js';
import { SdkContractError } from '../../src/contract/errors.js';
import { toHex, type OaepEncryptEvidenceRecord, type OaepDecryptEvidenceRecord } from '../../src/evidence/record.js';
import { CHROMIUM_WEBCRYPTO } from '../schema/backend-identity.js';
import type { ExecutionAdapter } from './engine.js';
import { getSharedChromiumPage } from './chromium-page.js';

function realization(): string {
  return `chromium ${CHROMIUM_WEBCRYPTO.apiVersion} (${CHROMIUM_WEBCRYPTO.sourcePin})`;
}

function hexToBase64Url(hex: string): string {
  return Buffer.from(hex, 'hex').toString('base64url');
}

// A real RSA-3072 key, supplied externally by the caller (e.g. generated
// once via Node's own webcrypto.subtle.generateKey), never generated by
// this Chromium wiring itself -- Phase A's own baseline uses ONE
// consistent key across all three backends' round-trip checks.
//
// Finding, confirmed by direct reproduction before wiring the fix: unlike
// Crypto++/Bouncy Castle's own raw-integer constructors (n, e, d alone
// suffice), Chromium's crypto.subtle.importKey('jwk', ...) for an RSA
// PRIVATE key strictly requires the full CRT parameter set (p, q, dp, dq,
// qi) -- omitting them throws DataError ("required JWK member \"p\" was
// missing"), even though d alone is mathematically sufficient to decrypt.
// These fields are therefore REQUIRED here for decrypt, not optional.
export interface OaepKeyHex {
  readonly modulusHex: string;
  readonly publicExponentHex: string;
  readonly privateExponentHex?: string; // required for decrypt
  readonly pHex?: string;
  readonly qHex?: string;
  readonly dpHex?: string;
  readonly dqHex?: string;
  readonly qiHex?: string;
}

function buildEncryptScript(jwk: object, plaintextHex: string, labelHex: string | null): string {
  const argsJson = JSON.stringify({ jwk, plaintextHex, labelHex });
  return `
    (async () => {
      const args = ${argsJson};
      const hexToBytes = (hex) => {
        const out = new Uint8Array(new ArrayBuffer(hex.length / 2));
        for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
        return out;
      };
      const key = await crypto.subtle.importKey('jwk', args.jwk, { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['encrypt']);
      const algo = { name: 'RSA-OAEP' };
      if (args.labelHex !== null) algo.label = hexToBytes(args.labelHex);
      const ctBuffer = await crypto.subtle.encrypt(algo, key, hexToBytes(args.plaintextHex));
      return Array.from(new Uint8Array(ctBuffer)).map((b) => b.toString(16).padStart(2, '0')).join('');
    })()
  `;
}

function buildDecryptScript(jwk: object, ciphertextHex: string, labelHex: string | null): string {
  const argsJson = JSON.stringify({ jwk, ciphertextHex, labelHex });
  return `
    (async () => {
      const args = ${argsJson};
      const hexToBytes = (hex) => {
        const out = new Uint8Array(new ArrayBuffer(hex.length / 2));
        for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
        return out;
      };
      try {
        const key = await crypto.subtle.importKey('jwk', args.jwk, { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['decrypt']);
        const algo = { name: 'RSA-OAEP' };
        if (args.labelHex !== null) algo.label = hexToBytes(args.labelHex);
        const ptBuffer = await crypto.subtle.decrypt(algo, key, hexToBytes(args.ciphertextHex));
        return { ok: true, plaintextHex: Array.from(new Uint8Array(ptBuffer)).map((b) => b.toString(16).padStart(2, '0')).join('') };
      } catch (e) {
        return { ok: false, message: String(e && e.message ? e.message : e) };
      }
    })()
  `;
}

function publicJwk(key: OaepKeyHex): object {
  return { kty: 'RSA', n: hexToBase64Url(key.modulusHex), e: hexToBase64Url(key.publicExponentHex), ext: true };
}

export function makeOaepEncryptChromiumAdapter(key: OaepKeyHex): ExecutionAdapter<OaepEncryptRequest, OaepEncryptEvidenceRecord> {
  return {
    operation: 'oaep',
    backend: CHROMIUM_WEBCRYPTO,
    execute: async (fixture) => {
      const input = { keyRole: fixture.key.role, modulusBits: fixture.key.modulusBits, plaintextHex: toHex(fixture.plaintext), labelHex: fixture.label === undefined ? null : toHex(fixture.label), hash: fixture.hash, mgfHash: fixture.mgfHash };
      try {
        validateOaepEncryptRequest(fixture); // Accept_C -- real M1 contract function, unmodified
        const page = await getSharedChromiumPage();
        const ciphertextHex: string = await page.evaluate(buildEncryptScript(publicJwk(key), input.plaintextHex, input.labelHex));
        return {
          operation: 'RSA-OAEP', direction: 'encrypt',
          backend: { name: 'webcrypto', realization: realization() },
          clauseIds: ['oaep.key', 'oaep.modulus', 'oaep.hash', 'oaep.mgfCoupling', 'oaep.label', 'oaep.message'],
          mutationId: null, input,
          outcome: { kind: 'accept', ciphertextHex },
          timestampIso: new Date().toISOString(),
        };
      } catch (err) {
        if (err instanceof SdkContractError) {
          return {
            operation: 'RSA-OAEP', direction: 'encrypt',
            backend: { name: 'webcrypto', realization: realization() },
            clauseIds: err.clauseIds, mutationId: null, input,
            outcome: { kind: 'reject', errorClass: err.errorClass, detail: err.message },
            timestampIso: new Date().toISOString(),
          };
        }
        throw err;
      }
    },
    toEvidenceFields: (_fixture, record) => ({
      subject: { backend: CHROMIUM_WEBCRYPTO, direction: 'encrypt', path: 'sdk' },
      input: { kind: 'oaep-encrypt-request', value: record.input },
      output: record.outcome.kind === 'accept' ? { kind: 'oaep-ciphertext', bytes: record.outcome.ciphertextHex } : undefined,
      outcome: record.outcome.kind === 'accept' ? { kind: 'accept' } : { kind: 'reject', detail: `${record.outcome.errorClass}: ${record.outcome.detail}` },
      clauseIdsEvaluated: record.clauseIds,
      executionStatus: 'completed',
      nativeObservation: undefined,
    }),
  };
}

export function makeOaepDecryptChromiumAdapter(key: OaepKeyHex): ExecutionAdapter<OaepDecryptRequest, OaepDecryptEvidenceRecord> {
  const privateJwk = {
    ...publicJwk(key),
    d: hexToBase64Url(key.privateExponentHex ?? ''),
    p: hexToBase64Url(key.pHex ?? ''),
    q: hexToBase64Url(key.qHex ?? ''),
    dp: hexToBase64Url(key.dpHex ?? ''),
    dq: hexToBase64Url(key.dqHex ?? ''),
    qi: hexToBase64Url(key.qiHex ?? ''),
  };
  return {
    operation: 'oaep',
    backend: CHROMIUM_WEBCRYPTO,
    execute: async (fixture) => {
      const input = { keyRole: fixture.key.role, modulusBits: fixture.key.modulusBits, ciphertextHex: toHex(fixture.ciphertext), labelHex: fixture.label === undefined ? null : toHex(fixture.label), hash: fixture.hash, mgfHash: fixture.mgfHash };
      try {
        validateOaepDecryptRequest(fixture); // Accept_C -- real M1 contract function, unmodified (deliberately no ciphertext-length check, D-034)
        const page = await getSharedChromiumPage();
        const result: { ok: boolean; plaintextHex?: string; message?: string } = await page.evaluate(buildDecryptScript(privateJwk, input.ciphertextHex, input.labelHex));
        if (!result.ok) {
          return {
            operation: 'RSA-OAEP', direction: 'decrypt',
            backend: { name: 'webcrypto', realization: realization() },
            clauseIds: ['oaep.error'], mutationId: null, input,
            outcome: { kind: 'reject', errorClass: 'decryption_error', detail: result.message ?? 'decrypt failed' },
            timestampIso: new Date().toISOString(),
          };
        }
        return {
          operation: 'RSA-OAEP', direction: 'decrypt',
          backend: { name: 'webcrypto', realization: realization() },
          clauseIds: ['oaep.key', 'oaep.modulus', 'oaep.hash', 'oaep.mgfCoupling', 'oaep.label'],
          mutationId: null, input,
          outcome: { kind: 'accept', plaintextHex: result.plaintextHex! },
          timestampIso: new Date().toISOString(),
        };
      } catch (err) {
        if (err instanceof SdkContractError) {
          return {
            operation: 'RSA-OAEP', direction: 'decrypt',
            backend: { name: 'webcrypto', realization: realization() },
            clauseIds: err.clauseIds, mutationId: null, input,
            outcome: { kind: 'reject', errorClass: err.errorClass, detail: err.message },
            timestampIso: new Date().toISOString(),
          };
        }
        throw err;
      }
    },
    toEvidenceFields: (_fixture, record) => ({
      subject: { backend: CHROMIUM_WEBCRYPTO, direction: 'decrypt', path: 'sdk' },
      input: { kind: 'oaep-decrypt-request', value: record.input },
      output: record.outcome.kind === 'accept' ? { kind: 'oaep-plaintext', bytes: record.outcome.plaintextHex } : undefined,
      outcome: record.outcome.kind === 'accept' ? { kind: 'accept' } : { kind: 'reject', detail: `${record.outcome.errorClass}: ${record.outcome.detail}` },
      clauseIdsEvaluated: record.clauseIds,
      executionStatus: 'completed',
      nativeObservation: undefined,
    }),
  };
}
