import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';

import { executeBaseline } from '../../../harness/orchestration/engine.js';
import { makeOaepEncryptChromiumAdapter, makeOaepDecryptChromiumAdapter, type OaepKeyHex } from '../../../harness/orchestration/oaep-chromium-wiring.js';
import { makeOaepEncryptCryptoppAdapter, makeOaepDecryptCryptoppAdapter, makeOaepEncryptBouncyCastleAdapter, makeOaepDecryptBouncyCastleAdapter } from '../../../harness/orchestration/oaep-native-wiring.js';
import { closeSharedChromium } from '../../../harness/orchestration/chromium-page.js';
import { makeRelationObservation } from '../../../harness/evidence/relation-observation.js';
import type { BaselineResult } from '../../../harness/evidence/baseline-result.js';
import { CHROMIUM_WEBCRYPTO, CRYPTOPP, BOUNCY_CASTLE, backendIdentityEquals } from '../../../harness/schema/backend-identity.js';
import type { OaepEncryptRequest, OaepDecryptRequest } from '../../../src/contract/oaep.js';

after(async () => {
  await closeSharedChromium();
});

// ONE real RSA-3072 key pair, generated once via Node's own WebCrypto
// (genuine cryptography -- legitimate at the M2.5 orchestration layer,
// unlike M2.4.6's mutation-only boundary), shared across all three
// backends' Phase A round-trip checks. Never generated by the backend
// wiring itself.
let oaepKey: OaepKeyHex;

function hexFromBase64Url(b64u: string): string {
  return Buffer.from(b64u, 'base64url').toString('hex');
}

test('setup: generate ONE real RSA-3072 OAEP key pair via Node WebCrypto, shared across all three backends', async () => {
  const keyPair = await webcrypto.subtle.generateKey(
    { name: 'RSA-OAEP', modulusLength: 3072, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' },
    true, ['encrypt', 'decrypt'],
  );
  const jwk = await webcrypto.subtle.exportKey('jwk', keyPair.privateKey);
  oaepKey = {
    modulusHex: hexFromBase64Url(jwk.n!),
    publicExponentHex: hexFromBase64Url(jwk.e!),
    privateExponentHex: hexFromBase64Url(jwk.d!),
    pHex: hexFromBase64Url(jwk.p!),
    qHex: hexFromBase64Url(jwk.q!),
    dpHex: hexFromBase64Url(jwk.dp!),
    dqHex: hexFromBase64Url(jwk.dq!),
    qiHex: hexFromBase64Url(jwk.qi!),
  };
  assert.equal(oaepKey.modulusHex.length, 768, '3072 bits = 384 bytes = 768 hex chars');
});

function encryptFixture(): OaepEncryptRequest {
  return {
    key: { role: 'public', modulusBits: 3072 },
    plaintext: Buffer.from('deadbeefdeadbeefdeadbeefdeadbeef', 'hex'),
    label: undefined, hash: 'SHA-256', mgfHash: 'SHA-256',
  };
}
function decryptFixture(ciphertextHex: string): OaepDecryptRequest {
  return {
    key: { role: 'private', modulusBits: 3072 },
    ciphertext: Buffer.from(ciphertextHex, 'hex'),
    label: undefined, hash: 'SHA-256', mgfHash: 'SHA-256',
  };
}

const BACKEND_FACTORIES = [
  { name: 'Chromium', encrypt: makeOaepEncryptChromiumAdapter, decrypt: makeOaepDecryptChromiumAdapter, expectedBackend: CHROMIUM_WEBCRYPTO },
  { name: 'Crypto++', encrypt: makeOaepEncryptCryptoppAdapter, decrypt: makeOaepDecryptCryptoppAdapter, expectedBackend: CRYPTOPP },
  { name: 'Bouncy Castle', encrypt: makeOaepEncryptBouncyCastleAdapter, decrypt: makeOaepDecryptBouncyCastleAdapter, expectedBackend: BOUNCY_CASTLE },
] as const;

for (const { name, encrypt, decrypt, expectedBackend } of BACKEND_FACTORIES) {
  test(`Phase A, OAEP x ${name}: real LOCAL round-trip -- Dec_p(Enc_p(m)) = m, ciphertext NEVER compared across providers (OAEP is probabilistic, Applicability(R_byte,OAEP)=0)`, async () => {
    const plaintext = encryptFixture();
    const encEvidence = await executeBaseline('A', `phase-a-oaep-enc-${name}`, plaintext, encrypt(oaepKey));
    assert.equal(encEvidence.outcome.kind, 'accept');
    assert.ok(backendIdentityEquals(encEvidence.subject.backend, expectedBackend));

    const ciphertextHex = (encEvidence.output as { bytes: string }).bytes;
    const decEvidence = await executeBaseline('A', `phase-a-oaep-dec-${name}`, decryptFixture(ciphertextHex), decrypt(oaepKey));
    assert.equal(decEvidence.outcome.kind, 'accept');
    assert.equal((decEvidence.output as { bytes: string }).bytes, 'deadbeefdeadbeefdeadbeefdeadbeef');
    assert.ok(backendIdentityEquals(decEvidence.subject.backend, expectedBackend));
  });
}

test('OAEP Phase A: three independent encryptions of the SAME plaintext produce DIFFERENT ciphertexts even on the SAME backend (probabilistic padding) -- confirms we are not accidentally testing a deterministic scheme', async () => {
  const plaintext = encryptFixture();
  const e1 = await executeBaseline('A', 'oaep-prob-1', plaintext, makeOaepEncryptCryptoppAdapter(oaepKey));
  const e2 = await executeBaseline('A', 'oaep-prob-2', plaintext, makeOaepEncryptCryptoppAdapter(oaepKey));
  assert.notEqual((e1.output as { bytes: string }).bytes, (e2.output as { bytes: string }).bytes);
});

test('OAEP Phase A: BaselineResult.complete=true, 3/3 cells -- built from real round-trip observations, never a raw ciphertext-equality comparison', async () => {
  const results: Array<{ backend: typeof CHROMIUM_WEBCRYPTO; ok: boolean }> = [];
  for (const { encrypt, decrypt, expectedBackend } of BACKEND_FACTORIES) {
    const enc = await executeBaseline('A', 'oaep-all-enc', encryptFixture(), encrypt(oaepKey));
    const dec = await executeBaseline('A', 'oaep-all-dec', decryptFixture((enc.output as { bytes: string }).bytes), decrypt(oaepKey));
    results.push({ backend: expectedBackend, ok: dec.outcome.kind === 'accept' && (dec.output as { bytes: string }).bytes === 'deadbeefdeadbeefdeadbeefdeadbeef' });
  }
  assert.ok(results.every((r) => r.ok));

  const observations = results.map((r) =>
    makeRelationObservation({
      applicable: true, context: { kind: 'baseline', phase: 'A', baselineInstanceId: 'oaep-all' }, relation: 'R_val',
      scope: { kind: 'single-backend', backend: r.backend }, status: 'pass', participants: [],
      evaluatorId: 'R_val', basis: 'OAEP Phase A local round-trip, real execution',
    }),
  );
  const baseline: BaselineResult = { baselineInstanceId: 'phase-a-oaep-3of3', phase: 'A', operation: 'oaep', observations: observations.map((o) => o.observationId), complete: true };
  assert.equal(baseline.complete, true);
  assert.equal(baseline.observations.length, 3);
});
