// Bloque C1 -- the pre-registered ground-truth table.
//
// AUTHORED ONCE from contractual evidence, then frozen as the source. The
// independent probe re-derives every entry and REFUTES this table:
//
//     Derive(c,s) != Registry(c,s)  =>  FAIL      never  Registry <- Derive
//
// One row per (mutationId, stimulusInstanceId). A premise is present iff its
// relation is applicable AND the relation has an object for that class; it is
// ABSENT otherwise, never defaulted. The rules referenced by ruleId are stated
// once in rules.ts rather than repeated ninety times; the citations are
// per-entry because traceability has to be granular even when the normative
// logic is not.
//
// Clause citations are the clauses the contractual consumer actually raised,
// obtained by probe -- never a plausible-looking one. For an ACCEPT no
// individual clause fires, so the anchor is the clause that DEFINES the
// acceptance boundary for that operation (GT-VAL-ACCEPT-ANCHOR).
//
// No provider was consulted anywhere. The five cryptographic entries rest on
// gcm.authentication, whose frozen text is unambiguous -- "any modification to
// IV/AAD/C/T must not authenticate" -- and on pss.verification, not on what
// Chromium, Crypto++ or Bouncy Castle happen to do.

import type { GroundTruthRow } from './types.js';

export const GROUND_TRUTH_TABLE: ReadonlyMap<string, GroundTruthRow> = new Map([
  ['HKDF-NULL-VS-EMPTY-SALT::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-INFO-TAMPER::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-IKM-NORMALIZATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-HASH-MISMATCH::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-LENGTH-WITHIN-DOMAIN-PERTURBATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-LENGTH-BOUNDARY-CROSSING::L=0', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['hkdf.length'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['hkdf.length'] } }],
  ['HKDF-LENGTH-BOUNDARY-CROSSING::L=8161', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['hkdf.length'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['hkdf.length'] } }],
  ['HKDF-UNSUPPORTED-HASH-DECLARATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['hkdf.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' } }],
  ['HKDF-CAPABILITY-BOUNDARY-MISMATCH::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' } }],
  ['GCM-PLAINTEXT-NORMALIZATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['GCM-AAD-ABSENT-EMPTY-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['GCM-AAD-IGNORED::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['GCM-IV-INTERPRETATION-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['GCM-CIPHERTEXT-COMPUTATION-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['GCM-AUTHENTICATION-BYPASS::TAG-TAMPER', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'error-expected', errorClass: 'authentication_failure', clauseIds: ['gcm.authentication'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.authentication'] } }],
  ['GCM-AUTHENTICATION-BYPASS::AAD-TAMPER', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'error-expected', errorClass: 'authentication_failure', clauseIds: ['gcm.authentication'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.authentication'] } }],
  ['GCM-AUTHENTICATION-BYPASS::IV-TAMPER', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'error-expected', errorClass: 'authentication_failure', clauseIds: ['gcm.authentication'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.authentication'] } }],
  ['GCM-AUTHENTICATION-BYPASS::CIPHERTEXT-TAMPER', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'error-expected', errorClass: 'authentication_failure', clauseIds: ['gcm.authentication'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.authentication'] } }],
  ['GCM-ARTIFACT-C-T-SWAP::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['gcm.validation'] }, errorExpectation: { kind: 'error-expected', errorClass: 'authentication_failure', clauseIds: ['gcm.authentication'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.authentication'] } }],
  ['GCM-ARTIFACT-STRUCTURE-CORRUPTION::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.artifact'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['gcm.artifact'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['gcm.artifact'] } }],
  ['GCM-KEY-PROFILE-BOUNDARY-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.key'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['gcm.key'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' } }],
  ['GCM-IV-PROFILE-BOUNDARY-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.iv'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['gcm.iv'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' } }],
  ['GCM-TAGLENGTH-PROFILE-BOUNDARY-BYPASS::tagLength-80', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.tagLength'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['gcm.tagLength'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' } }],
  ['GCM-TAGLENGTH-PROFILE-BOUNDARY-BYPASS::tagLength-below-floor-16', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.tagLength'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['gcm.tagLength'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' } }],
  ['GCM-TAGLENGTH-PROFILE-BOUNDARY-BYPASS::tagLength-below-floor-0', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['gcm.tagLength'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['gcm.tagLength'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' } }],
  ['GCM-PROVIDER-CAPABILITY-MISMATCH::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
  ['GCM-ERROR-MISCLASSIFICATION::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
  ['OAEP-MESSAGE-NORMALIZATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['oaep.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['OAEP-CIPHERTEXT-COMPUTATION-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['oaep.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['OAEP-CIPHERTEXT-LENGTH-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['oaep.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['OAEP-MODULUS-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.modulus'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['oaep.modulus'] } }],
  ['OAEP-HASH-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.hash'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['oaep.hash'] } }],
  ['OAEP-MGF-COUPLING-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.mgfCoupling'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['oaep.mgfCoupling'] } }],
  ['OAEP-LABEL-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.label'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['oaep.label'] } }],
  ['OAEP-MESSAGE-BOUNDARY-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.message'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['oaep.message'] } }],
  ['OAEP-KEY-ROLE-BYPASS::encrypt-with-private', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.key'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['oaep.key'] } }],
  ['OAEP-KEY-ROLE-BYPASS::decrypt-with-public', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['oaep.key'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['oaep.key'] }, expectedOutcome: { kind: 'reject', clauseIds: ['oaep.key'] } }],
  ['OAEP-RANDOMNESS-INTERFACE-LEAK::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['oaep.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['OAEP-DECRYPT-ERROR-DISCLOSURE::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' } }],
  ['OAEP-PROVIDER-CAPABILITY-MISREPORT::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' } }],
  ['PSS-SIGN-MESSAGE-NORMALIZATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-VERIFY-MESSAGE-NORMALIZATION::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-SIGNATURE-COMPUTATION-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-SIGNATURE-LENGTH-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-MODULUS-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['pss.modulus'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['pss.modulus'] } }],
  ['PSS-HASH-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['pss.hash'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['pss.hash'] } }],
  ['PSS-MGF-COUPLING-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['pss.mgfCoupling'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['pss.mgfCoupling'] } }],
  ['PSS-SALTLENGTH-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['pss.saltLength'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['pss.saltLength'] } }],
  ['PSS-KEY-ROLE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['pss.key'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['pss.key'] } }],
  ['PSS-RNG-INTERFACE-LEAK::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-SALT-BYTES-INTERFACE-LEAK::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['pss.validation'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-VERIFICATION-FALSE-ACCEPT::default', { expectedValidation: { decision: { kind: 'verified', value: false }, clauseIds: ['pss.verification'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-VERIFY' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-VERIFICATION-FALSE-REJECT::default', { expectedValidation: { decision: { kind: 'verified', value: true }, clauseIds: ['pss.verification'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-VERIFY' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['PSS-ERROR-MISCLASSIFICATION::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' } }],
  ['PSS-PROVIDER-CAPABILITY-MISREPORT::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' } }],
  ['RSA-SER-PUBLIC-MATERIAL-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['rsa-ser.der-syntax', 'rsa-ser.container', 'rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['RSA-SER-PRIVATE-MATERIAL-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['rsa-ser.der-syntax', 'rsa-ser.container', 'rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['RSA-SER-DER-IMPORT-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['rsa-ser.exact-consumption'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.exact-consumption'] } }],
  ['RSA-SER-DER-EXPORT-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.public-validity'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.public-validity'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.public-validity'] } }],
  ['RSA-SER-CONTAINER-IMPORT-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.container'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['rsa-ser.container'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.container'] } }],
  ['RSA-SER-CONTAINER-EXPORT-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['rsa-ser.der-syntax', 'rsa-ser.container', 'rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['RSA-SER-TRAILING-DATA-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['rsa-ser.exact-consumption'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.exact-consumption'] } }],
  ['RSA-SER-ROLE-CONTAINER-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.role-container'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['rsa-ser.role-container'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.role-container'] } }],
  ['RSA-SER-OID-IMPORT-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.algorithm-id'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['rsa-ser.algorithm-id'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.algorithm-id'] } }],
  ['RSA-SER-OID-EXPORT-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['rsa-ser.der-syntax', 'rsa-ser.container', 'rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['RSA-SER-PARAMETERS-IMPORT-PROFILE-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.algorithm-params'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['rsa-ser.algorithm-params'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.algorithm-params'] } }],
  ['RSA-SER-PARAMETERS-EXPORT-CANONICALIZATION-DIVERGENCE::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['rsa-ser.der-syntax', 'rsa-ser.container', 'rsa-ser.exact-consumption'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['RSA-SER-PUBLIC-VALIDITY-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.public-validity'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.public-validity'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.public-validity'] } }],
  ['RSA-SER-PRIVATE-DOMAIN-BYPASS::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-domain'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-domain'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-domain'] } }],
  ['RSA-SER-PRIVATE-RELATIONAL-BYPASS::n-neq-pq', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-relations'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-relations'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-relations'] } }],
  ['RSA-SER-PRIVATE-RELATIONAL-BYPASS::ed-not-1', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-relations'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-relations'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-relations'] } }],
  ['RSA-SER-PRIVATE-RELATIONAL-BYPASS::edP-not-1', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-relations'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-relations'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-relations'] } }],
  ['RSA-SER-PRIVATE-RELATIONAL-BYPASS::edQ-not-1', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-relations'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-relations'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-relations'] } }],
  ['RSA-SER-PRIVATE-RELATIONAL-BYPASS::qqInv-not-1', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['rsa-ser.private-relations'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['rsa-ser.private-relations'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['rsa-ser.private-relations'] } }],
  ['RSA-SER-ERROR-MISCLASSIFICATION::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
  ['RSA-SER-PROVIDER-CAPABILITY-MISREPORT::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
  ['EC-ROLE-CONTAINER-MISMATCH::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.key.role'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['ec-ser.key.role'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.key.role'] } }],
  ['EC-CURVE-SUBSTITUTION::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.curve'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['ec-ser.curve'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.curve'] } }],
  ['EC-PUBLIC-POINT-ENCODING::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.public.point'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['ec-ser.public.point'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.public.point'] } }],
  ['EC-PUBLIC-OFF-CURVE::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.curveMembership'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_membership', clauseIds: ['ec-ser.curveMembership'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.curveMembership'] } }],
  ['EC-PRIVATE-SCALAR-RANGE::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.private.scalar'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['ec-ser.private.scalar'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.private.scalar'] } }],
  ['EC-PRIVATE-PAIR-MISMATCH::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.pairConsistency'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_key', clauseIds: ['ec-ser.pairConsistency'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.pairConsistency'] } }],
  ['EC-PUBLIC-DER-MALFORMED::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.validation.syntax'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['ec-ser.validation.syntax'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.validation.syntax'] } }],
  ['EC-PRIVATE-DER-MALFORMED::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.validation.syntax'] }, errorExpectation: { kind: 'error-expected', errorClass: 'malformed_artifact', clauseIds: ['ec-ser.validation.syntax'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.validation.syntax'] } }],
  ['EC-PRIVATE-PARAMS-ABSENT::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['ec-ser.validation.syntax', 'ec-ser.validation.semantic'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['EC-PRIVATE-PARAMS-MISMATCH::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.key.role'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['ec-ser.key.role'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.key.role'] } }],
  ['EC-PRIVATE-PUBKEY-ABSENT::default', { expectedValidation: { decision: { kind: 'reject' }, clauseIds: ['ec-ser.key.role'] }, errorExpectation: { kind: 'error-expected', errorClass: 'invalid_parameter', clauseIds: ['ec-ser.key.role'] }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'reject', clauseIds: ['ec-ser.key.role'] } }],
  ['EC-NATIVE-EXPORT-LEAK::default', { expectedValidation: { decision: { kind: 'accept' }, clauseIds: ['ec-ser.validation.syntax', 'ec-ser.validation.semantic'] }, errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-ACCEPT' }, checksRequired: { basis: 'both', ruleId: 'GT-SER-BOTH' }, expectedOutcome: { kind: 'normal', ruleId: 'GT-INTEROP-ROUNDTRIP' } }],
  ['EC-ERROR-MAP-SWAP::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
  ['EC-CAPABILITY-MANIFEST-MISMATCH::default', { errorExpectation: { kind: 'no-error-expected', ruleId: 'GT-ERR-DECLARATIVE' }, checksRequired: { basis: 'representation-conformance', ruleId: 'GT-SER-DECLARATIVE' } }],
]);
